spring:
  application:
    name: crud

  datasource:
    url: jdbc:postgresql://localhost:5432/example-crud
    username: postgres
    password: groot
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update       # Other options: create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090
